# This is a basic workflow to help you get started with Actions

name: file-test-pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: create folder named test and create three files named file2.txt, file3.txt and file4.txt with content "This is file2", "This is file3" and "This is file4" respectively
        run: |
          mkdir test
          cd test
          echo "This is file2" > file2.txt
          echo "This is file3" > file3.txt
          echo "This is file4" > file4.txt

      - name: create folder named test2 amd copy the files from file3.txt and file4.txt from test folder to test2 folder
        run: |
          mkdir test2
          cp test/file3.txt test2/file3.txt
          cp test/file4.txt test2/file4.txt 

      - name : Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: file4.txt       
          path: test2/file4.txt
          retention-days: 7